// <auto-generated />
using BeyzaNurCansever.OneDrive.Masaüstü.YazLab1.ShopApp.ShopApp.Data.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ShopApp.data.Migrations
{
    [DbContext(typeof(ShopContext))]
    partial class ShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("BeyzaNurCansever.OneDrive.Masaüstü.YazLab1.ShopApp.ShopApp.entity.Laptop", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("DiskBoyutu")
                        .IsRequired()
                        .HasColumnName("Disk_boyutu")
                        .HasColumnType("TEXT")
                        .IsFixedLength(true)
                        .HasMaxLength(10);

                    b.Property<string>("DiskTuru")
                        .IsRequired()
                        .HasColumnName("Disk_türü")
                        .HasColumnType("TEXT")
                        .IsFixedLength(true)
                        .HasMaxLength(10);

                    b.Property<string>("EkranBoyutu")
                        .IsRequired()
                        .HasColumnName("Ekran_boyutu")
                        .HasColumnType("TEXT")
                        .IsFixedLength(true)
                        .HasMaxLength(10);

                    b.Property<string>("IslemciTipi")
                        .IsRequired()
                        .HasColumnName("Islemci_tipi")
                        .HasColumnType("TEXT")
                        .IsFixedLength(true)
                        .HasMaxLength(20);

                    b.Property<string>("Islemci_nesli")
                        .HasColumnType("TEXT");

                    b.Property<string>("IsletimSistemi")
                        .IsRequired()
                        .HasColumnName("Isletim_sistemi")
                        .HasColumnType("TEXT")
                        .IsFixedLength(true)
                        .HasMaxLength(20);

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .IsFixedLength(true)
                        .HasMaxLength(10);

                    b.Property<string>("ModelAdı")
                        .IsRequired()
                        .HasColumnName("Model_adı")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ram")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .IsFixedLength(true)
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("Laptop");
                });

            modelBuilder.Entity("BeyzaNurCansever.OneDrive.Masaüstü.YazLab1.ShopApp.ShopApp.entity.LaptopSite", b =>
                {
                    b.Property<int>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LaptopId")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Puan")
                        .HasColumnType("INTEGER");

                    b.HasKey("SiteId", "LaptopId")
                        .HasName("PK_ModelSite");

                    b.HasIndex("LaptopId");

                    b.ToTable("LaptopSite");
                });

            modelBuilder.Entity("BeyzaNurCansever.OneDrive.Masaüstü.YazLab1.ShopApp.ShopApp.entity.Site", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .IsFixedLength(true)
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("Site");
                });

            modelBuilder.Entity("BeyzaNurCansever.OneDrive.Masaüstü.YazLab1.ShopApp.ShopApp.entity.LaptopSite", b =>
                {
                    b.HasOne("BeyzaNurCansever.OneDrive.Masaüstü.YazLab1.ShopApp.ShopApp.entity.Laptop", "Laptop")
                        .WithMany("LaptopSites")
                        .HasForeignKey("LaptopId")
                        .HasConstraintName("FK_ModelSite_Model")
                        .IsRequired();

                    b.HasOne("BeyzaNurCansever.OneDrive.Masaüstü.YazLab1.ShopApp.ShopApp.entity.Site", "Site")
                        .WithMany("LaptopSites")
                        .HasForeignKey("SiteId")
                        .HasConstraintName("FK_ModelSite_Site")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
